### ISSUE TITLE
How build manual

### ISSUE THREAD

**Issue by mshalmanov** [plane000/Minecraft#13]
Hello. This is good project.

Need add build manual for this project. What is workspase use and how to build crossplatform ?

I can help if need.

**Comment by benkyd** [comment]
The project is not in a ready state but should be able to build with cmake on windows and linux

**Comment by mshalmanov** [comment]
I clone this project to my debian (Linux mint) and install cmake latest use this command
[make.log](https://github.com/benkyd/Minecraft/files/8671436/make.log)

```
Install Cmake to debian 10

	sudo apt update

	sudo apt upgrade

	sudo apt install build-essential checkinstall zlib1g-dev libssl-dev
	
	sudo apt install libsdl2-dev libglm-dev -y
	
	wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz

	tar -zxvf cmake-3.22.2.tar.gz

	cd cmake-3.22.2

	sudo ./bootstrap

	sudo make

	sudo make install

	cmake --version

Build project to Debian 10
	
	cd Minecraft
	
	sudo cmake .
```

When i can run sudo make in the project directory, i take many errors. I copy and save this many errors in the make.log file and attached there.

**Comment by mshalmanov** [comment]
I clone this project to my debian (Linux mint) and install cmake latest use this command

```
Install Cmake to debian 10

	sudo apt update

	sudo apt upgrade

	sudo apt install build-essential checkinstall zlib1g-dev libssl-dev
	
	sudo apt install libsdl2-dev libglm-dev -y
	
	wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz

	tar -zxvf cmake-3.22.2.tar.gz

	cd cmake-3.22.2

	sudo ./bootstrap

	sudo make

	sudo make install

	cmake --version

Build project to Debian 10
	
	cd Minecraft
	
	sudo cmake .
```

When i can run sudo make in the project directory, i take many errors. I copy and save this many errors in the make.log file and attached there.
[make.LOG](https://github.com/benkyd/Minecraft/files/8671482/make.LOG)

**Comment by benkyd** [comment]
Only build [working_version](https://github.com/benkyd/Minecraft/tree/working_version)

To build 
```
mkdir build
cd build
cmake ..
make
```

**Comment by mshalmanov** [comment]
I execute command on the debian 10 terminal in the project folder

mkdir build
cd build
cmake ..
make

after make command, create  outpute file.

My result in the debian 10 terminal
[100%] Linking CXX executable output
[100%] Built target output

When will be executing game and how i can help to ?

**Comment by benkyd** [comment]
you must run `output`

**Comment by mshalmanov** [comment]
Hello.
After build project, i run output file in the build folder with command ./output. 
I take errors
![image](https://user-images.githubusercontent.com/4174493/211204475-c7e2dfd6-6d1c-4c81-99ad-6f08597e9076.png)

What am I doing wrong ?
Please help me.

**Comment by benkyd** [comment]
What branch are you on?

**Comment by mshalmanov** [comment]
> What branch are you on?

from [working_version](https://github.com/benkyd/Minecraft/tree/working_version)

**Comment by benkyd** [comment]
Did a window open? Doesn't look like a world initialised
